### ISSUE TITLE
FAQs aren't themed

### ISSUE THREAD

**Issue by banoodle** [kanopi/saplings-component-types#41]
I'm not sure what they should look like, but the FAQs are currently unthemed.

I think we should either theme them or consider removing them.

![Screenshot 2024-06-18 at 4 40 25 PM](https://github.com/kanopi/saplings-component-types/assets/7685811/93ca8494-37d6-4e1c-aa7e-7ea1ad1a7abc)

On most builds, it seems the accordion component is what we tend to use for FAQs, but if we want to include this component, perhaps something like [this](https://shuffle.dev/editor?project=9c4159d5364b716430c2dfd2388e251f91b09af3&tutorial=1) would be good as base theming for this component.

**Comment by thejimbirch** [comment]
In a different ticket, I fixed the formatting.  There was an errant `</div>`.  Not sure this is still needed.  @kmurphychi247

**Comment by thejimbirch** [comment]
Fixed.
